package com.fiverr.foodwasteapp.models;

/**
 * Order Class is the request that the user make to receiver a donation
 * Change conform new attributes
 */
public class Order {

    // Id Order is an unique identifier, generated by Server
    // use only into the server to each order is unique
    String idOrder;
    // Business object is the foundation, charity organization, etc
    // that have the donation
    Business business;
    // Person object is the user that request the donation
    Person person;

    // DateDelivery is the delivery date that is in long type because is in milliseconds format
    // Change conform you database server is configured
    long dateDelivery;
    // TimeDelivery is the delivery time that is in long type because is in milliseconds format
    // Change conform you database server is configured
    long timeDelivery;

    // This variable identify if the request is approved or not
    // When Order object is create this value is always FALSE
    boolean isApproved = false;

    /**
     * Constructor to create the order, could to be to use for person how for the foundation
     * @param idOrder is an unique identifier, generated by Server
     * @param business is the foundation, charity organization, etc; that have the donation
     * @param person is the user that request the donation
     * @param dateDelivery is the delivery date that is in long type because is in milliseconds format
     * @param timeDelivery is the delivery time that is in long type because is in milliseconds format
     */
    public Order(String idOrder, Business business, Person person, long dateDelivery, long timeDelivery) {
        this.idOrder = idOrder;
        this.business = business;
        this.person = person;
        this.dateDelivery = dateDelivery;
        this.timeDelivery = timeDelivery;
    }

    /**
     * Getter the ID Order
     * @return id
     */
    public String getIdOrder() {
        return idOrder;
    }

    /**
     * Setter the ID Order
     * @param idOrder is an unique identifier into the server
     */
    public void setIdOrder(String idOrder) {
        this.idOrder = idOrder;
    }

    /**
     * Getter the Business Order
     * @return business
     */
    public Business getBusiness() {
        return business;
    }

    /**
     * Setter the Business Object
     * @param business the foundation, charity organization, etc; that have the donation
     */
    public void setBusiness(Business business) {
        this.business = business;
    }

    /**
     * Getter Person object
     * @return object
     */
    public Person getPerson() {
        return person;
    }

    /**
     * Setter the Person object
     * @param person is the user that request the donation
     */
    public void setPerson(Person person) {
        this.person = person;
    }

    /**
     * Getter the Delivery Date long
     * @return delivery date in format long
     */
    public long getDateDelivery() {
        return dateDelivery;
    }

    /**
     * Setter the Delivery Date
     * @param dateDelivery is the delivery date that is in long type because is in milliseconds format
     */
    public void setDateDelivery(long dateDelivery) {
        this.dateDelivery = dateDelivery;
    }

    /**
     * Getter the Delivery time long
     * @return delivery time in format long
     */
    public long getTimeDelivery() {
        return timeDelivery;
    }

    /**
     * Setter the Delivery Time
     * @param timeDelivery is the delivery time that is in long type because is in milliseconds format
     */
    public void setTimeDelivery(long timeDelivery) {
        this.timeDelivery = timeDelivery;
    }

    /**
     * Getter the isApproved boolean
     * @return boolean value isApproved
     */
    public boolean isApproved() {
        return isApproved;
    }

    /**
     * Setter isApproved
     * @param approved This variable identify if the request is approved or not
     */
    public void setApproved(boolean approved) {
        isApproved = approved;
    }
}
